import Head from "next/head";
import type { NextPage } from "next";
import React, { useRef, useEffect } from "react";

import Navbar from "../components/navbar";
import HeroSection from "../components/hero-section";
import SkillSection from "../components/skill-section";
import ProjectSection from "../components/project-section";
import Footer from "../components/footer";
import ObjectiveSection from "../components/objective-section";

const Home: NextPage = () => {
  return (
    <div className="bg-midnight-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="flex flex-col min-h-screen items-center font-mono text-midnight-100">
        <div>
          <HeroSection />
        </div>
        <div className="flex justify-center items-center sm:w-screen min-h-[800px] bg-midnight-100/10">
          <ObjectiveSection />
        </div>
        <div>
          <SkillSection />
        </div>
        <div>
          <ProjectSection />
        </div>
      </main>

      <footer className="flex justify-center items-center p-4 bg-midnight-100/50 text-white">
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
