import Head from "next/head";
import type { NextPage } from "next";

import Navbar from "../components/navbar";
import HeroSection from "../components/hero-section";
import ObjectiveSection from "../components/objective-section";
import SkillSection from "../components/skill-section";
import ProjectSection from "../components/project-section";
import ContactSection from "../components/contact-section";
import Footer from "../components/footer";

const Home: NextPage = () => {
	return (
		<div className="bg-midnight-200">
			<Head>
				<>Create Next App</>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />
			<main className="flex flex-col items-center font-mono text-midnight-100 mb-20 sm:mb-0 gap-10 pb-10">
				<div>
					<HeroSection />
				</div>
				<div
					id="objective"
					className="flex justify-center items-center w-screen min-h-screen sm:py-20 bg-gradient-to-r from-blue-101 to-green-101"
				>
					<ObjectiveSection />
				</div>
				<div
					id="skills"
					className="flex justify-center items-center w-screen min-h-screen"
				>
					<SkillSection />
				</div>
				<div
					id="projects"
					className="flex justify-center items-center w-full max-w-full sm:w-screen h-screen"
				>
					<ProjectSection />
				</div>
				<div
					id="contact"
					className="flex justify-center items-center sm:w-screen"
				>
					<ContactSection />
				</div>
			</main>

			<footer className="flex justify-center items-center p-4 bg-midnight-100/50 text-white">
				<Footer />
			</footer>
		</div>
	);
};

export default Home;
