import Head from "next/head";
import type { NextPage } from "next";

import Navbar from "../components/navbar";
import HeroSection from "../components/hero-section";
import ObjectiveSection from "../components/objective-section";
import SkillSection from "../components/skill-section";
import ProjectSection from "../components/project-section";
import ContactSection from "../components/contact-section";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <div className="bg-midnight-200">
      <Head>
        <>Create Next App</>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="flex flex-col min-h-screen items-center font-mono text-midnight-100 mb-20 sm:mb-0">
        <div>
          <HeroSection />
        </div>
        <div
          id="objective"
          className="flex justify-center items-center sm:w-screen min-h-[800px] sm:min-h-0 sm:py-20 bg-slate-100/70"
        >
          <ObjectiveSection />
        </div>
        <div
          id="skills"
          className="flex justify-center items-center sm:w-screen py-40"
        >
          <SkillSection />
        </div>
        <div
          id="projects"
          className="flex justify-center items-center sm:w-screen min-h-[700px]"
        >
          <ProjectSection />
        </div>
        <div
          id="contact"
          className="flex justify-center items-center sm:w-screen min-h-[700px]"
        >
          <ContactSection />
        </div>
      </main>

      <footer className="flex justify-center items-center p-4 bg-midnight-100/50 text-white">
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
